### ISSUE TITLE
Readme should have a sample config for multiple fans

### ISSUE THREAD

**Issue by ghulands** [sean9keenan/homebridge-bigAssFans#10]
It didn't take much to work it out, but for others it might be good to have a sample

**Comment by sean9keenan** [comment]
Updated the readme to explain how the new "platform" way of adding bigAssFan support inherently supports multiple fans.

Unfortunately the "legacy" way of doing it will not support multiple cameras, I think you'll get a port binding error if you try to do that unfortunately :/
