### ISSUE TITLE
about 1/3 of the time one of my two fans would not be usable in the home app

### ISSUE THREAD

**Issue by pponce** [sean9keenan/homebridge-bigAssFans#12]
I was running into an issue where 1 of my two fans would not be usable in the homekit app. They would be present as options in the app (fan and light) but for one of the fans the buttons in homekit would not do anything.
I'm forgetting the exact error message but it would say 2 accessories not responding or not usable. Something like that.  It would be one fan and it's light.

I looked at the code and tried adding this to my config file.
"fan_count": 2
Since adding this to my config file I have not received this error. So this seems to have fixed my problem.
Sharing my issue and solution in case others have the same problem. Also in case there is a better way to solve for it in the code somehow.

**Comment by sean9keenan** [comment]
This is an excellent catch @pponce - I actually completely forgot that I put this as an option in the config - I will update the readme now.
