### ISSUE TITLE
Does not work with 2 Fans added as accessories

### ISSUE THREAD

**Issue by smokey-live** [sean9keenan/homebridge-bigAssFans#2]
I just installed this home bridge plugin and it works fantastically for a single fan. It crashes when I add more than 1 fan as an accessory. Any progress on getting this to work with 2 fans?

Thanks!

**Comment by sean9keenan** [comment]
Thanks for the more descriptive ticket than #1 👍 Will close this one when I close #1 as well. See updates over there for the time being

**Comment by sean9keenan** [comment]
Should be working now
