### ISSUE TITLE
Enabling this platform makes homekit stall and fail to update all other devices

### ISSUE THREAD

**Issue by bdraco** [sean9keenan/homebridge-bigAssFans#25]
If this platform is enabled it causes homekit to stall and or fail to update everything.    It seems like the code is looping somewhere which is probably the root cause of https://github.com/sean9keenan/homebridge-bigAssFans/commit/fee5fa095dcc6a6d36686d9a000d82074e6cb4d8

**Comment by newformula** [comment]
@bdraco do you know if this is still an issue? I’d like to try and integrate haiku’s into Homebridge / Homekit but won’t spend the time playing if there are dealbreakers at the moment.

**Comment by bdraco** [comment]
I haven't tested this recently as I'm now using HASS for this, however it suffers from the same issue so I currently have it turned off

**Comment by newformula** [comment]
Just as a follow up for anyone who reads this, I just set up my first Haiku L with wifi module via this homebridge plugin and it was seamless - via HooBs running on a Raspberry Pi. No issues with HomeKit stalling yet.
