### ISSUE TITLE
Occupancy Sensor - Always triggered 

### ISSUE THREAD

**Issue by kylecwhite** [sean9keenan/homebridge-bigAssFans#35]
The occupancy sensor is always triggered in HomeKit. It has always been like this since I installed it. Any chance it can be fixed?

**Comment by jasonanovak** [comment]
I'm having the same issue. I did a little bit of digging and I'm using this homebridge plugin to control Haiku L fans, which I don't think have an occupancy sensor.  Just guessing that this configuration results in the expected-but-not-present motion senors always triggering in HomeKit.

**Comment by jasonanovak** [comment]
I haven't tried this but it looks like PR #32 may be related to this? @barkmadley do you know if your PR resolves this issue?

**Comment by jtroest** [comment]
Is there still any development on this plugin? It has been quiet for almost two years it looks like, This is hands down the best one for these fans that I have seen and it would be nice to get this thing working.

**Comment by jensmoes** [comment]
> I haven't tried this but it looks like PR #32 may be related to this? @barkmadley do you know if your PR resolves this issue?

It did for me using the Haiku fan.

**Comment by sean9keenan** [comment]
> Is there still any development on this plugin? It has been quiet for almost two years it looks like.

Not really :(.

I just haven't been able to devote time to working on this, and don't actually keep homebridge running (although I really should)

I did just merge in #32, thanks for reminding me, and republished the npm package - so hopefully it just works if you re-install 🤞 🤞.

I'm going to close the issue - but feel free to reopen if it doesn't.

> This is hands down the best one for these fans
The fan is really great - I totally agree!
